title: "Tim's Homelab Projects"
description: My journey with homelab projects to develop my I.T. skills!
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

favicon: "/assets/icons/favicon-32x32.png"

url: "https://timsmithh23.github.io"

aux_links:
  My LinkedIn: [https://www.linkedin.com/in/tim-smithh23/]

# Remove default Just the Docs footer text h
footer_content: ""

# Hide posts from the sidebar/nav by default
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      nav_exclude: true

just_the_docs:
  custom_css:
    - "assets/css/custom.css"
  custom_js:
    - "assets/js/lightbox.js"
  color_scheme_toggle: true
  color_scheme_default: auto
