title: Tims Homelabs
description: My journey with homelab projects to develop my I.T. skills!
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: "https://timsmithh23.github.io"

aux_links:
  My LinkedIn: [https://www.linkedin.com/in/timsmithh23/]
