# Site Configuration for Jekyll with Chirpy theme

# Import the theme (mandatory)
theme: jekyll-theme-chirpy

# Language for the site (use language codes, e.g. 'en' for English)
lang: en

# Timezone for date/time display, use tz database names
timezone: America/New_York

# Main site info for SEO and display
title: Tims Homelabs # Main title of your site
tagline: WEBSITE IN PROGRESS. Some links may or may not be broken! # Subtitle
description: >- # Used for SEO meta and RSS feed
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Your site URL (no trailing slash)
url: "https://www.timsmithh23.github.io"

# GitHub username (used by Chirpy for links, etc)
github:
  username: timsmithh23

# Social info about the author/site owner
social:
  name: Tim Smith # Your full name
  email: tim.smithh23@gmail.com # Your contact email
  links:
    - https://twitter.com/username # Replace with your Twitter URL
    - https://github.com/timsmithh23 # Your GitHub URL
    # Add more links by adding more lines here

# Site verification codes (optional, fill if you use these services)
webmaster_verifications:
  google: 
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Analytics tracking IDs (optional, fill if you use these services)
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

# Page views provider (only supports 'goatcounter' for now)
pageviews:
  provider:

# Default color scheme of the site ('light', 'dark', or empty for system default)
theme_mode:

# CDN URL for media resources, e.g. avatar or images (optional)
cdn:

# Sidebar avatar image URL or local path (optional)
avatar:

# Social preview image URL (for SEO OpenGraph, optional)
social_preview_image:

# Enable or disable Table of Contents in posts
toc: true

# Comments system config (choose one and fill it if you want comments)
comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Custom CSS asset file path (relative to /assets/css/)
assets: /assets/css/main.scss

# Self-hosted static assets options (advanced)
self_host:
  enabled: false
  env:

# Progressive Web App (PWA) options
pwa:
  enabled: true # Allow installable PWA
  cache:
    enabled: true # Enable offline caching
    deny_paths:
      # - "/example" # Paths to exclude from cache

# Number of posts per page on pagination
paginate: 10

# Base URL if your site is hosted under a subdirectory (usually blank for github.io)
baseurl: ""

# Markdown parser and syntax highlighter settings
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections configuration (for tabs or other custom content types)
collections:
  tabs:
    output: true
    sort_by: order

# Default front-matter values for posts, drafts, and tabs
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# CSS compression style
sass:
  style: compressed

# HTML compression settings
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Files or folders to exclude from build
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# Jekyll Archives plugin settings for categories and tags
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: blog   # change this from 'tag' to 'blog'
  permalinks:
    tag: /blogs/:name/   # change URL path from /tags/ to /blogs/
    category: /categories/:name/
